C229_G4/Models/Club.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace C229_G4.Models
{
    public class Club
    {
        public int ClubId { get; set; }
        [Required(ErrorMessage = "Please enter club name")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Club Name cannot have numbers & special characters")]
        public string ClubName { get; set; }
        [Required(ErrorMessage = "Please enter stadium name")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Stadium Name cannot have numbers & special characters")]
        public string StadiumName { get; set; }
        [Required(ErrorMessage = "Please enter year founded")]
        [Range(1700, 2020, ErrorMessage = "Please enter year in range of 1700-2020")]
        public int? YearFounded { get; set; }
        [Required(ErrorMessage = "Please enter club country")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Country Name cannot have numbers, spaces & special characters")]
        public string Country { get; set; }
        public List<Player> Players { get; set; } = new List<Player>();
    }
}

C229_G4/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using C229_G4.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace C229_G4.Controllers
{
    [Authorize(Roles = "R_Admin")]
    public class ClubController : Controller
    {
        private IClubRepository repository;

        public ClubController(IClubRepository repo)
        {
            repository = repo;
        }

        [AllowAnonymous]
        public ViewResult ListClubs(string sortOrder, string searchClubName)
        {
            ViewData["ClubIdSort"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["ClubNameSort"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["SearchFilter"] = searchClubName;

            var clubs = repository.Clubs;
            if (!String.IsNullOrEmpty(searchClubName))
            {
                clubs = clubs.Where(c => c.ClubName.Contains(searchClubName));
            }
            
            switch (sortOrder)
            {
                case "id_desc":
                    clubs = clubs.OrderByDescending(c => c.ClubId);
                    break;
                case "name":
                    clubs = clubs.OrderBy(c => c.ClubName);
                    break;
                case "name_desc":
                    clubs = clubs.OrderByDescending(c => c.ClubName);
                    break;
                default:
                    clubs = clubs.OrderBy(c => c.ClubId);
                    break;
            }
            return View(clubs);
        }

        [AllowAnonymous]
        public ViewResult ClubDetails(int clubId)
        {
            var result = repository.Clubs.FirstOrDefault(c => c.ClubId == clubId);
            return View(result ?? new Club());
        }
        
        public ViewResult AddClub()
        {
            return View("AddClub", new Club());
        }
        
        [HttpGet]
        public ViewResult EditClub(int clubId)
        {
            return View("AddClub", repository.Clubs.FirstOrDefault(c => c.ClubId == clubId));
        }
        
        [HttpPost]
        public IActionResult SaveClub(Club aClub)
        {
            if (ModelState.IsValid)
            {
                if(aClub.ClubId == 0)
                {
                    TempData["message"] = $"{aClub.ClubName} was added successfully";
                }
                else
                {
                    TempData["message"] = $"{aClub.ClubName} was updated successfully";
                }
                repository.SaveClub(aClub);
                ModelState.Clear();
                return RedirectToAction("ListClubs");
            }
            else
            {
                return View("AddClub", aClub);
            }
            
        }
        
        [HttpPost]
        public IActionResult DeleteClub(int clubId)
        {
            Club deletedClub = repository.DeleteClub(clubId);
            if (deletedClub != null)
            {
                TempData["message"] = $"{deletedClub.ClubName} was deleted successfully";
            }
            return RedirectToAction("ListClubs");
        }
        
    }
}

C229_G4/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using C229_G4.Models;
using C229_G4.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace C229_G4.Controllers
{
    [Authorize]
    public class PlayerController : Controller
    {
        private IClubRepository repository;

        public PlayerController(IClubRepository repo)
        {
            repository = repo;
        }

        public ViewResult ListPlayers(string sortOrder, string searchPlayerName)
        {
            ViewData["PlayerIdSort"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["PlayerNameSort"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["PlayerAgeSort"] = sortOrder == "age" ? "age_desc" : "age";
            ViewData["PlayerCountrySort"] = sortOrder == "country" ? "country_desc" : "country";
            ViewData["PlayerClubIdSort"] = sortOrder == "clubid" ? "clubid_desc" : "clubid";
            ViewData["SearchFilter"] = searchPlayerName;

            var players = repository.Players;
            if (!String.IsNullOrEmpty(searchPlayerName))
            {
                players = players.Where(p => p.PlayerName.Contains(searchPlayerName));
            }

            switch (sortOrder)
            {
                case "id_desc":
                    players = players.OrderByDescending(p => p.PlayerId);
                    break;
                case "name":
                    players = players.OrderBy(p => p.PlayerName);
                    break;
                case "name_desc":
                    players = players.OrderByDescending(p => p.PlayerName);
                    break;
                case "age":
                    players = players.OrderBy(p => p.Age);
                    break;
                case "age_desc":
                    players = players.OrderByDescending(p => p.Age);
                    break;
                case "country":
                    players = players.OrderBy(p => p.Country);
                    break;
                case "country_desc":
                    players = players.OrderByDescending(p => p.Country);
                    break;
                case "clubid":
                    players = players.OrderBy(p => p.ClubId);
                    break;
                case "clubid_desc":
                    players = players.OrderByDescending(p => p.ClubId);
                    break;
                default:
                    players = players.OrderBy(p => p.PlayerId);
                    break;
            }
            return View(players);
        }
        
        [HttpGet]
        public ViewResult EditPlayer(int playerId)
        {
            return View("ManagePlayers", new PlayersClubsViewModel() { Player = repository.Players.FirstOrDefault(p => p.PlayerId == playerId), Clubs = repository.Clubs, Players = repository.Players.Where(p => p.PlayerId == playerId) });
        }

        [HttpPost]
        public IActionResult DeletePlayer(int playerId)
        {
            Player deletedPlayer = repository.DeletePlayer(playerId);
            if (deletedPlayer != null)
            {
                TempData["message"] = $"{deletedPlayer.PlayerName} was deleted successfully";
            }
            return RedirectToAction("ListPlayers");
        }

        [HttpGet]
        public ViewResult ManagePlayers(int clubId)
        {
            return View(new PlayersClubsViewModel() { Player = new Player { ClubId = clubId }, Clubs = repository.Clubs, Players = repository.Players });
        }

        [HttpPost]
        public IActionResult AddPlayer(Player player)
        {
            if (ModelState.IsValid)
            {
                if (player.PlayerId == 0)
                {
                    TempData["message"] = $"{player.PlayerName} was added successfully";
                }
                else
                {
                    TempData["message"] = $"{player.PlayerName} was updated successfully";
                }
                repository.SavePlayer(player);
                ModelState.Clear();
                return RedirectToAction("ListPlayers");
            }
            else
            {
                if(player.PlayerId == 0)
                {
                    return View("ManagePlayers", new PlayersClubsViewModel() { Player = new Player { ClubId = 0}, Clubs = repository.Clubs, Players = repository.Players });
                }
                else
                {
                    return View("ManagePlayers", new PlayersClubsViewModel() { Player = repository.Players.FirstOrDefault(p => p.PlayerId == player.PlayerId), Clubs = repository.Clubs, Players = repository.Players.Where(p => p.PlayerId == player.PlayerId) });
                }
            }

        }

        [HttpPost]
        public IActionResult ReassignPlayer(int playerId, int clubId)
        {
            var player = repository.Players.FirstOrDefault(p => p.PlayerId == playerId);
            player.ClubId = clubId;
            repository.SavePlayer(player);
            return RedirectToAction("ListPlayers");
        }

        [HttpPost]
        public IActionResult DeregisterPlayer(int playerId)
        {
            var player = repository.Players.FirstOrDefault(p => p.PlayerId == playerId);
            player.ClubId = null;
            repository.SavePlayer(player);
            return RedirectToAction("ListPlayers");
        }
    }
}

C229_G4/Views/Shared/ClubForm.cshtml
@model Club

<input type="hidden" asp-for="ClubId" />
<div>
    <label asp-for="ClubName">Club Name</label><br />
    <input asp-for="ClubName" />
</div>

<div>
    <label asp-for="StadiumName">Stadium Name</label><br />
    <input asp-for="StadiumName" />
</div>

<div>
    <label asp-for="YearFounded">Year Founded</label><br />
    <input asp-for="YearFounded" />
</div>

<div>
    <label asp-for="Country">Country</label><br />
    <input asp-for="Country" />
</div>

C229_G4/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="~/lib/jquery/core.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>
</head>
<body>
    <div class="header">
        <img src="~/images/logo_transparent.png" alt="Logo.png" />
        <div class="header-right">
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Club" asp-action="ListClubs">Clubs</a></li>
            </ul>
        </div>

    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    <div>
        @RenderBody()
    </div>
</body>
</html>

C229_G4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div class="header">
        <img src="~/images/logo_transparent.png" alt="Logo.png" />
        <div class="header-right">
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Club" asp-action="ListClubs">Clubs</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole("R_Admin"))
                    {
                        <li><a asp-controller="Club" asp-action="AddClub">Add Club</a></li>
                        <li><a asp-controller="Player" asp-action="ListPlayers">Players</a></li>
                        <li><a asp-controller="Player" asp-action="ManagePlayers">Manage Players</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Player" asp-action="ListPlayers">Players</a></li>
                        <li><a asp-controller="Player" asp-action="ManagePlayers">Manage Players</a></li>
                    }
                    <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                }
                else
                {
                    <li><a asp-controller="Account" asp-action="Login">Login</a></li>
                }
            </ul>
        </div>
        
    </div>
    <div>
        @RenderBody()
    </div>
    <div class="footer">
        <h4>&copy; C229_G4 FC SportPro 2019</h4>
        <h5>CaihuiFu(301040187) SubodhKantRai(301018368)  HardeepSingh(301034240)</h5>
        <h6>Best viewed at 1920*1080</h6>
    </div>
</body>
</html>